Server:
  Jira: "https://my.jira.server.com"
  Confluence: "https://my.confluence.server.com"

Projects:
  Project name:
    JQL: "project = TEST"
    Report:
      Engine: "PlantUML"
      Space: "SPACE"
      Parent page: "My Parent Page"
    Fields:
      Start date: "Start date (WBSGantt)"
      End date: "Finish date (WBSGantt)"
      Link: "is blocked by"
