server:
  jira: "https://my.jira.server.com"
  confluence: "https://my.confluence.server.com"

report: &PyGanttReport
  space: "SPACE"
  parent_page: "My Parent Page"
  engine: "PlantUML"

fields: &WbsFields
  start_date: "Start date (WBSGantt)"
  end_date: "Finish date (WBSGantt)"

projects:
  - name: "Project name"
    jql: "project = TEST"
    report: *PyGanttReport
    fields: *WbsFields
  - name: "Second project name"
    jql: "project = TEST2"
    report: *PyGanttReport
    fields: *WbsFields
